### ISSUE TITLE
iOS code signing for xcodeworkspace that contains two xcodeproj

### ISSUE THREAD

**Issue by guoguoguilai** [codemagic-ci-cd/codemagic-docs#579]
I am using codemagic to build CI/CD pipeline for my Flutter project. My project contains two xcodeproj in xcodeworkspace, and the bundle id are different. I failed following this documents[[1](https://blog.codemagic.io/how-to-code-sign-publish-ios-apps/ ) [2](https://docs.codemagic.io/flutter-code-signing/ios-code-signing/)]

How to do iOS code signing for a xcodeworkspace that contains two xcodeproj?

**Comment by icarusdust** [comment]
Hi, if you are using flavors, then I am assuming that you have already implemented the required steps via Xcode. Sadly, I am not quite sure what the issue is from the above-mentioned description. Could you please join our community slack channel and forward the question to there ? Or you can send an email to nihal@nevercode.io directly.

**Comment by fixer112** [comment]
Am also having same issue
